---
title: "Model Form Check"
author: "Blain Morin"
date: "1/17/2022"
output: pdf_document
classoption: 
  - landscape
urlcolor: blue
header-includes:
   - \usepackage{geometry}
   - \usepackage{placeins}
   - \usepackage{amsmath} 
   - \usepackage{bm}
   - \usepackage{lscape}
   - \usepackage{rotating}
   - \newcommand{\vect}[1]{\boldsymbol{\mathbf{#1}}}
   - \newcommand{\blandscape}{\begin{landscape}}
   - \newcommand{\elandscape}{\end{landscape}}
---


```{r setup, include=FALSE}

### Document Settings
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(ctsem)
library(rstan)
library(kableExtra)
library(shinystan)

```




```{r, results = 'asis'}

load("~/dynamic_bulldoze2/outputs/model1")

cat(ctModelLatex(model, textsize = 'small', compile = FALSE, equationonly = TRUE))


```

```{r eval=FALSE, fig.height=12, fig.width=16, include=FALSE}


ctKalman(model, 
         plot = TRUE,
         subjects = c(1:14),
         kalmanvec = c("etasmooth", "y", "ysmooth"),
         timestep = .5) 


```

```{r eval=FALSE, include=FALSE}


launch_shinystan(model$stanfit$stanfit)

```